language: python
python:
  - "3.6"
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - mv travis_adbkey adbkey
  - mv travis_adbkey.pub adbkey.pub

