################################################################
## Packages / Bin Pickup
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'Bin Pickup'

      expose: &expose
        <<: *customize
        expose: true

      not-expose: &not-expose
        <<: *customize
        expose: false

    ################################################
    ## Bin Pickup
    ################################################

    # vacuum.xiaomi_vacuum_cleaner:
    #   <<: *customize
    #   friendly_name: "Bob"

################################################
## Bin Pickup - Sensor's
################################################

sensor:

      #################################################################
      ##   Green Bin
      #################################################################

- platform: template
  sensors:
    rubbish_pickup_day:
      friendly_name: Rubbish Pickup Day
      value_template: >
        {% set whatpickupweek = strptime(states.calendar.rubbish_day.attributes.start_time, "%Y-%m-%d %H:%M:%S").strftime("%U") %}
        {% set pickupday = strptime(states.calendar.rubbish_day.attributes.start_time, "%Y-%m-%d %H:%M:%S").strftime("%A") %}
        {% if whatpickupweek > now().strftime("%U") %}
          {{ strptime(states.calendar.rubbish_day.attributes.start_time, "%Y-%m-%d %H:%M:%S").strftime("%A %d %b") }}
        {% elif pickupday == now().strftime("%A") %}
          - TODAY -
        {% elif pickupday == (as_timestamp(now()) + (86400)) | timestamp_custom("%A",true) %}
          TOMORROW
        {% else %}
          {{ pickupday }}
        {% endif %}

      #################################################################
      ##   Blue Bin
      #################################################################

- platform: template
  sensors:
    recycling_pickup_day:
      friendly_name: Recycling Pickup Day
      value_template: >
        {% set whatpickupweek = strptime(states.calendar.recycling_day.attributes.start_time, "%Y-%m-%d %H:%M:%S").strftime("%U") %}
        {% set pickupday = strptime(states.calendar.recycling_day.attributes.start_time, "%Y-%m-%d %H:%M:%S").strftime("%A") %}
        {% if whatpickupweek > now().strftime("%U") %}
          {{ strptime(states.calendar.recycling_day.attributes.start_time, "%Y-%m-%d %H:%M:%S").strftime("%A %d %b") }}
        {% elif pickupday == now().strftime("%A") %}
          - TODAY -
        {% elif pickupday == (as_timestamp(now()) + (86400)) | timestamp_custom("%A",true) %}
          TOMORROW
        {% else %}
          {{ pickupday }}
        {% endif %}

################################################
## Bin Pickup - Group
################################################

group:

      #################################################################
      ##  Bin Card
      #################################################################

bins:
  name: Bins
  entities:
    - sensor.rubbish_pickup_day
    - sensor.recycling_pickup_day
