################################################################
## Packages / Birthday
## shamlessly "borrowed" from @skalavala
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'birthday'

      expose: &expose
        <<: *customize
        hidden: false

      not-expose: &not-expose
        <<: *customize
        hidden: true

    input_label.lara_birthday:
      <<: *not-expose
    input_label.jack_birthday:
      <<: *not-expose
    input_label.mollie_birthday:
      <<: *not-expose
    input_label.kitten_birthday:
      <<: *not-expose

input_label:
  lara_birthday:
    value: !secret lara_birthday
  jack_birthday:
    value: !secret jack_birthday
  mollie_birthday:
    value: !secret mollie_birthday
  kitten_birthday:
    value: !secret kitten_birthday

  lara_birthday_days2go:
    icon: mdi:cake-variant
    name: Lara's Birthday
  jack_birthday_days2go:
    icon: mdi:cake-variant
    name: Jack's Birthday
  mollie_birthday_days2go:
    icon: mdi:cake-variant
    name: Mollie's Birthday
  kitten_birthday_days2go:
    icon: mdi:cake-variant
    name: Kitten's Birthday

group:
  Birthday Countdown:
    entities:
      - input_label.jack_birthday_days2go
      - input_label.lara_birthday_days2go
      - input_label.mollie_birthday_days2go
      - input_label.kitten_birthday_days2go

automation:

###############################################################################
# Build the excitement
###############################################################################

- alias: Birthday Countdown 30 Days
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id:
      - input_label.lara_birthday_days2go
      - input_label.jack_birthday_days2go
      - input_label.mollie_birthday_days2go
      - input_label.kitten_birthday_days2go
  condition:
    - condition: state
      entity_id: group.all_devices
      state: 'home'
    - condition: time
      after: '18:00:00'
      before: '21:00:00'
    - condition: template
      value_template: "{{ trigger.to_state.state | int > 0 and trigger.to_state.state | int < 30 }}"
  action:
    - service: script.google_notify
      data_template:
        message: "{{ trigger.entity_id.split('.')[1].split('_')[0] | title }}'s Birthday is only {{ trigger.to_state.state }} days to go!"

###############################################################################
# Celebrate Birthday!!!
###############################################################################

- alias: Today is the Birthday
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id:
      - input_label.lara_birthday_days2go
      - input_label.jack_birthday_days2go
      - input_label.mollie_birthday_days2go
      - input_label.kitten_birthday_days2go
  condition:
    - condition: state
      entity_id: group.all_devices
      state: 'home'
    - condition: time
      after: '18:00:00'
      before: '22:00:00'
    - condition: template
      value_template: "{{ trigger.to_state.state | int == 0 }}"
  action:
    - service: script.google_notify
      data_template:
        message: "Hurray! Today is {{ trigger.entity_id.split('.')[1].split('_')[0] | title }}'s Birthday!"

###############################################################################
# Announce Happy Birthday message every hour starting 7 am until 9 PM
###############################################################################
#
#
# - alias: Random Birthday Wishes
#   initial_state: true
#   hide_entity: true
#   trigger:
#     platform: time
#     hours: '/1'
#     minutes: 3
#     seconds: 00
#   condition:
#     condition: and
#     conditions:
#       - condition: state
#         entity_id: group.all_devices
#         state: 'home'
#       - condition: time
#         after: '07:00:00'
#         before: '21:00:00'
#       - condition: or
#         conditions:
#           - condition: template
#             value_template: "{{ states.input_label.lara_birthday_days2go.state | int == 0 }}"
#           - condition: template
#             value_template: "{{ states.input_label.jack_birthday_days2go.state | int == 0 }}"
#           - condition: template
#             value_template: "{{ states.input_label.mollie_birthday_days2go.state | int == 0 }}"
#           - condition: template
#             value_template: "{{ states.input_label.kitten_birthday_days2go.state | int == 0 }}"
#   action:
#     - service: script.google_notify
#       data_template:
#         message: >
#           {% set msg = "" %}
#           {%- macro getEndGreeting() -%}
#             {%- if greeting |default('yes', true ) == "yes" -%}
#               Thank you!
#             {%- endif -%}
#           {%- endmacro -%}
#           {% set msg = msg + "<speak> " %}
#           {% set msg = msg + ". " + message %}
#           {% set msg = msg.replace(".", " <break time='0.5s'/> ") %}
#           {% set msg = msg + " " + getEndGreeting() %}
#           {% set msg = msg + " </speak>" %}
#           {{ msg }}




- alias: Update Birthdays
  initial_state: true
  hide_entity: true
  trigger:
    - platform: time_pattern
      minutes: '/5'
      seconds: 00
    - platform: homeassistant
      event: start
  condition:
    - condition: template
      value_template: "{{ states.input_label.lara_birthday.state.split('-') | length  > 0 }}"
    - condition: template
      value_template: "{{ states.input_label.jack_birthday.state.split('-') | length  > 0 }}"
    - condition: template
      value_template: "{{ states.input_label.mollie_birthday.state.split('-') | length  > 0 }}"
    - condition: template
      value_template: "{{ states.input_label.kitten_birthday.state.split('-') | length  > 0 }}"
  action:
    - service: input_label.set_value
      data_template:
        entity_id: input_label.lara_birthday_days2go
        value: >
          {% set year = states.sensor.date.state.split('-')[0] %}
          {% set month = states.sensor.date.state.split('-')[1] %}
          {% set date = states.sensor.date.state.split('-')[2] %}
          {% if states('input_label.lara_birthday') != "unknown" %}
            {%- set bDayMonth = states.input_label.lara_birthday.state.split('-')[0] -%}
            {%- set bDayDate = states.input_label.lara_birthday.state.split('-')[1] -%}
            {%- set numOfDays = ((as_timestamp(strptime(year ~ '-' ~ bDayMonth ~ '-' ~ bDayDate , '%Y-%m-%d')) | timestamp_custom('%j', true) | int ) - (as_timestamp(strptime(year ~ '-' ~ month~ '-' ~ date , '%Y-%m-%d')) | timestamp_custom('%j', true) | int)) -%}
            {%- if numOfDays < 0 -%}
              {{ numOfDays + 365 }}
            {%- else -%}
              {{ numOfDays }}
            {%- endif -%}
          {% else %}
            -
          {% endif %}
    - service: input_label.set_value
      data_template:
        entity_id: input_label.jack_birthday_days2go
        value: >
          {% set year = states.sensor.date.state.split('-')[0] %}
          {% set month = states.sensor.date.state.split('-')[1] %}
          {% set date = states.sensor.date.state.split('-')[2] %}
          {% if states('input_label.jack_birthday') != "unknown" %}
            {%- set bDayMonth = states.input_label.jack_birthday.state.split('-')[0] -%}
            {%- set bDayDate = states.input_label.jack_birthday.state.split('-')[1] -%}
            {%- set numOfDays = ((as_timestamp(strptime(year ~ '-' ~ bDayMonth ~ '-' ~ bDayDate , '%Y-%m-%d')) | timestamp_custom('%j', true) | int ) - (as_timestamp(strptime(year ~ '-' ~ month~ '-' ~ date , '%Y-%m-%d')) | timestamp_custom('%j', true) | int)) -%}
            {%- if numOfDays < 0 -%}
              {{ numOfDays + 365 }}
            {%- else -%}
              {{ numOfDays }}
            {%- endif -%}
          {% else %}
            -
          {% endif %}
    - service: input_label.set_value
      data_template:
        entity_id: input_label.mollie_birthday_days2go
        value: >
          {% set year = states.sensor.date.state.split('-')[0] %}
          {% set month = states.sensor.date.state.split('-')[1] %}
          {% set date = states.sensor.date.state.split('-')[2] %}
          {% if states('input_label.mollie_birthday') != "unknown" %}
            {%- set bDayMonth = states.input_label.mollie_birthday.state.split('-')[0] -%}
            {%- set bDayDate = states.input_label.mollie_birthday.state.split('-')[1] -%}
            {%- set numOfDays = ((as_timestamp(strptime(year ~ '-' ~ bDayMonth ~ '-' ~ bDayDate , '%Y-%m-%d')) | timestamp_custom('%j', true) | int ) - (as_timestamp(strptime(year ~ '-' ~ month~ '-' ~ date , '%Y-%m-%d')) | timestamp_custom('%j', true) | int)) -%}
            {%- if numOfDays < 0 -%}
              {{ numOfDays + 365 }}
            {%- else -%}
              {{ numOfDays }}
            {%- endif -%}
          {% else %}
            -
          {% endif %}
    - service: input_label.set_value
      data_template:
        entity_id: input_label.kitten_birthday_days2go
        value: >
          {% set year = states.sensor.date.state.split('-')[0] %}
          {% set month = states.sensor.date.state.split('-')[1] %}
          {% set date = states.sensor.date.state.split('-')[2] %}
          {% if states('input_label.kitten_birthday') != "unknown" %}
            {%- set bDayMonth = states.input_label.kitten_birthday.state.split('-')[0] -%}
            {%- set bDayDate = states.input_label.kitten_birthday.state.split('-')[1] -%}
            {%- set numOfDays = ((as_timestamp(strptime(year ~ '-' ~ bDayMonth ~ '-' ~ bDayDate , '%Y-%m-%d')) | timestamp_custom('%j', true) | int ) - (as_timestamp(strptime(year ~ '-' ~ month~ '-' ~ date , '%Y-%m-%d')) | timestamp_custom('%j', true) | int)) -%}
            {%- if numOfDays < 0 -%}
              {{ numOfDays + 365 }}
            {%- else -%}
              {{ numOfDays }}
            {%- endif -%}
          {% else %}
            -
          {% endif %}
