################################################################
## Packages / Speedtest
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'Speedtest'

      expose: &expose
        <<: *customize
        expose: false

    ################################################
    ## Speedtest
    ################################################

    # vacuum.xiaomi_vacuum_cleaner:
    #   <<: *customize
    #   friendly_name: "Bob"

################################################
## Speedtest - Sensor's
################################################

speedtestdotnet:

      #################################################################
      ## Speedtest.net
      #################################################################
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

################################################
## Speedtest - Group
################################################

group:

      #################################################################
      ## Weather Card
      #################################################################

  Internet:
    name: Internet
    entities:
     - sensor.speedtest_download
     - sensor.speedtest_upload
     - sensor.speedtest_ping
