################################################################
## Packages / TV
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'TV'

      expose: &expose
        <<: *customize
        hidden: false

      not-expose: &not-expose
        <<: *customize
        hidden: true

    ################################################
    ## TV
    ################################################

    media_player.sony_bravia_tv:
      friendly_name: Living Room TV
      <<: *expose

    binary_sensor.bedroom_tv:
      friendly_name: Bedroom TV
      initial_state: off
      <<: *expose

################################################
## TV - Media Player's
################################################

media_player:

      #################################################################
      ## TV - Living Room TV
      #################################################################

- platform: braviatv
  host: 192.168.1.57
  name: Living Room TV

#       #################################################################
#       ## TV - Living Room Fire TV
#       #################################################################

- platform: androidtv
  name: Living Room Fire TV
  host: 192.168.1.55
  adbkey: "/config/android/adbkey"

      #################################################################
      ## TV - Front Room TV
      #################################################################

- platform: braviatv
  host: 192.168.1.237
  name: Front Room TV

#       #################################################################
#       ## TV - Front Room Fire TV
#       #################################################################

# - platform: firetv
#   name: Front Room Fire TV
#   host: 192.168.1.157

#       #################################################################
#       ## TV - Bedroom Fire TV
#       #################################################################

# - platform: firetv
#   name: Bedroom Fire TV
#   host: 192.168.1.56

      #################################################################
      ## Media Player - Bedroom TV
      #################################################################


# - platform: broadlink
#   name: Bedroom TV
#   host: 192.168.1.164
#   mac: '34:EA:34:8E:E9:59'
#   ircodes_ini: 'custom_components/bedroom_tv.ini'

      #################################################################
      ## Media Player - Plex
      #################################################################


- platform: plex
  entity_namespace: 'plex'
  include_non_clients: true
  scan_interval: 5
  


# - platform: universal
#   name: Bedroom Universal
#   children:
#     - media_player.bedroom_fire_tv

################################################
## TV - switches
################################################

switch:

      #################################################################
      ## TV - Bedroom
      #################################################################

#
# - platform: broadlink
#   host: 192.168.1.164
#   mac: 34:EA:34:8E:E9:59
#   friendly_name: Upstairs IR Sender
#   timeout: 15
#   switches:
    # upstairs_tv_power:
    #   friendly_name: "Upstairs TV Power"
    #   command_on: 'JgBQAAABKJIUEBQREzYVEBMSExETEhMSEzYUNRMSEzYUNRQ2FDUTNhUQExITEhI3ExISEhMSExISNhQ2FDUUERM2EzYUNhQ1FAAFHgABKEkTAA0FAAAAAAAAAAA='
    #   command_off: 'JgBQAAABKJIUEBQREzYVEBMSExETEhMSEzYUNRMSEzYUNRQ2FDUTNhUQExITEhI3ExISEhMSExISNhQ2FDUUERM2EzYUNhQ1FAAFHgABKEkTAA0FAAAAAAAAAAA='
    # upstairs_tv_volume:
    #   friendly_name: "Upstairs TV Volume"
    #   command_on: 'JgBQAAABJZURFBETETgRFBMSEhMSEhITETgSNxEUEjcTNhM3ETgROBQREzYUEREUExEUERMSExERORMSEDkQORQ1FTQUNhE4FQAFHgABJkoRAA0FAAAAAAAAAAA='
    #   command_off: 'JgBQAAABJZUUEBMSEjcVEBITEhIRFBMSETgUNRUQETgVNBQ2FDUVNBM3EzYSExETERQSExETExISEhURETcVNRM2FTQRORA5FQAFHQABJUwQAA0FAAAAAAAAAAA='
    # upstairs_tv_eco:
    #   friendly_name: "Upstairs TV Eco Mode"
    #   command_on: 'JgBYAAABJZUQFBUQETgVEBEUEBQRFBEUEDkROBEUETgROBE5FDUVNBE5FBATNhQSEDgVEBEUETgVEBE4FRAQORUQEDkROBUQEQAFIwABJ0kVAAxIAAElTBQADQU='
    #   command_off: 'JgBYAAABJZUQFBUQETgVEBEUEBQRFBEUEDkROBEUETgROBE5FDUVNBE5FBATNhQSEDgVEBEUETgVEBE4FRAQORUQEDkROBUQEQAFIwABJ0kVAAxIAAElTBQADQU='
    # upstairs_tv_right:
    #   friendly_name: "Upstairs TV Right-Left"
    #   #Left#
    #   command_on: 'JgBYAAABJZUTERQREjcRFBMSEBQRFBITEDkTNhEUEzYTNxA5EzYTNhE5EzYROBMSERQTERQQEhQQFBMSExITNhE4FDUUNhE4EQAFIwABJ0oTAAxJAAElTBEADQU='
    #   #Right#
    #   command_off: 'JgBYAAABJZURFBETFDYRExMSERQRExQRETgTNxETEzcTNhE4ETgTNxETETkROBEUEhITEhEUERMRORETERQROBE4ETkROBE4EwAFIgABJUsRAAxMAAElSxEADQU='
    # upstairs_tv_up:
    #   friendly_name: "Upstairs TV Up-Down"
    #   #Up#
    #   command_on: 'JgBQAAABJZUSExISETgUEREUERMRFBMSETgTNhEUETgUNhE4ETgUNREUExIRExEUExIRExE5ERMRORE4ETgROBI4EjcRFBE4FAAFIAABKEkRAA0FAAAAAAAAAAA='
    #   #Down#
    #   command_off: 'JgBQAAABJZUUERAVEDgUERQRERQTEhAUETgUNRQRFDURORQ1ETgUNRQ2ExEUEhAUEhIRFBE4ERQRFBM2ETgVNRM2ETgVEBE4EQAFIwABJUwRAA0FAAAAAAAAAAA='

################################################
## TV - scripts
################################################

script:

      #################################################################
      ## Bedroom TV Scripts
      #################################################################

  upstairs_tv_power:
    sequence:
      - service: switch.turn_on
        entity_id: switch.upstairs_tv_power

  upstairs_tv_up:
    sequence:
      - service: switch.turn_on
        entity_id: switch.upstairs_tv_volume

  upstairs_tv_down:
    sequence:
      - service: switch.turn_off
        entity_id: switch.upstairs_tv_volume

      #################################################################
      ## Livingroom TV Scripts
      #################################################################

  living_room_tv_power:
    sequence:
      - service: media_player.toggle
        entity_id: media_player.living_room_tv

  living_room_tv_up:
    sequence:
      - service: media_player.volume_up
        entity_id: media_player.living_room_tv

  living_room_tv_down:
    sequence:
      - service: media_player.volume_down
        entity_id: media_player.living_room_tv

################################################
## TV - group
################################################

group:

      #################################################################
      ## Bedroom TV Group
      #################################################################

  bedroom_tv:
    name: Bedroom TV
    control: hidden
    entities:
      - script.upstairs_tv_power
      - script.upstairs_tv_up
      - script.upstairs_tv_down

      #################################################################
      ## Living Room TV Group
      #################################################################

  living_room_tv:
    name: Living Room TV
    control: hidden
    entities:
      - script.living_room_tv_power
      - script.living_room_tv_up
      - script.living_room_tv_down

################################################
## TV - binary_sensor
################################################

binary_sensor:

        #################################################################
        ## LWT MQTT Bedroom TV
        #################################################################

  - platform: mqtt
    name: "bedroom_tv"
    state_topic: "bedroom_tv/power"
    payload_on: "online"
    payload_off: "offline"
    device_class: power
